ITR_ui <- function() { fluidPage(fluidRow(column(size_pages,
                                                 h3('Quarterly  Financial Reports'),
                                                 p('Here you\'ll be able to download quarterly financial reports from the DFP system. ',
                                                   'Be aware that, this web interface only includes ', strong('active'), 
                                                   ' companies within B3. When using the R package, there is no such restriction.'),
                                                 p('After executing your query, a block of R code will appear, helping you using the R package in a R session.'),
                                                 hr())),
                                 fluidRow(column(size_pages,
                                                 selectInput('user_companies_itr', label = 'Select available companies', 
                                                             choices = c('All Companies', 
                                                                         available_companies), multiple=TRUE, selectize=TRUE, 
                                                             selected = available_companies[1], width = '100%'),
                                                 textOutput('user_companies_itr')
                                 )
                                 ),
                                 br(),
                                 fluidRow(column(size_pages,
                                                 dateRangeInput("daterange_itr", "Select date range:",
                                                                start = first_date,
                                                                end   = Sys.Date(),
                                                                min = as.Date('2010-01-01'),
                                                                startview = 'year'))
                                 ),
                                 br(),
                                 fluidRow(column(size_pages,
                                                 checkboxGroupInput("user_choice_type_docs_itr", "Selected Financial Statements:",
                                                                    choiceNames =
                                                                      list("BPA - Assets", 
                                                                           "BPP - Liabilities",
                                                                           "DRE - Income Statement",
                                                                           "DFC_MD - cash flow by direct method",
                                                                           "DFC_MI - cash flow by indirect method",
                                                                           "DMPL - statement of changes in equity",
                                                                           "DVA - value added report"),
                                                                    choiceValues = 
                                                                      list("BPA", "BPP", "DRE", "DFC_MD", 
                                                                           "DFC_MI", "DMPL", "DVA"), 
                                                                    selected = c("BPA", 'BPP', 'DRE')) )),
                                 br(),
                                 fluidRow(column(size_pages,
                                                 checkboxGroupInput("user_choice_type_format_itr", "Type of Statements:",
                                                                    choiceNames =
                                                                      list("Individual", 
                                                                           "Consolidated"),
                                                                    choiceValues = 
                                                                      list("con", "ind"), 
                                                                    selected = c("con", 'ind')) )),
                                 #br(),
                                 fluidRow(column(size_pages,
                                                 selectInput('format_output_itr', label = 'Download format', 
                                                             choices = c('Single Excel file (xlsx)', 
                                                                         'Single Zipped file with data as csv', 
                                                                         'Single RDS file (R native format)'),
                                                             multiple=FALSE, selected = 'Single Zipped file with data as csv')) ),
                                 br(),
                                 fluidRow(column(2,
                                                 actionButton('actionid_itr', 'Get Data!', icon = NULL, width = NULL)),
                                          column(3, 
                                                 conditionalPanel("input.actionid_itr != 0",
                                                                  verbatimTextOutput('text_action_id')))
                                 ),
                                 br(),
                                 fluidRow(column(size_pages, 
                                                 conditionalPanel("output.text_action_id_itr =='DONE. Hit download..'",
                                                                  downloadButton("downloadData", 'Download')))),
                                 br(),
                                 fluidRow(column(size_pages, 
                                                 conditionalPanel("output.text_action_id_itr =='DONE. Hit download..'",
                                                                  p('Your query can be replicated in R with the following script. Just copy it and execute in R: ')),
                                                 br(),
                                                 verbatimTextOutput('code_text'))),
)
}